apiVersion: v2
appVersion: v2.23.1
dependencies:
- alias: kubeclarity-postgresql
  condition: kubeclarity-postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.13
- alias: kubeclarity-trivy-server
  condition: kubeclarity-trivy-server.enabled
  name: trivy
  repository: https://aquasecurity.github.io/helm-charts
  version: 0.4.17
- alias: exporterchart
  condition: exporterchart.enabled
  name: exporterchart
  repository: /home/alper/tekchart/kubeclarity/charts/exporterchart
  version: 0.1.0
description: Charts for KubeClarity deployment.
home: https://github.com/openclarity/kubeclarity
icon: https://github.com/openclarity/kubeclarity/raw/main/images/kubeclarity-logo.png
maintainers:
- name: KubeClarity
  url: https://github.com/openclarity/kubeclarity
name: kubeclarity
sources:
- https://github.com/openclarity/kubeclarity
type: application
version: v2.23.1
