apiVersion: v1
kind: Service
metadata:
  name: {{ include "exporterchart.fullname" . }}
  labels:
    {{- include "exporterchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "exporterchart.selectorLabels" . | nindent 4 }}
